### ISSUE TITLE
Upload fails on md5 calculation

### ISSUE THREAD

**Issue by rlalik** [tcztzy/django-multiple-file-chunked-upload#1]
I am trying to use this module in my project. I had to apply only one change in views to generate dataset_name on fly without asking for form field for it, so I replaced
```
dataset = self.get_or_create_dataset(request.POST.get('dataset_name'))
```
with
```
dataset_name = "dsname_%s" % chunk._get_name()
dataset = self.get_or_create_dataset(dataset_name)
```
But now, when view executes this line:
```
if chunked_upload.is_finished:
```
it fails in the model in this part:
```
    @property
    def md5(self):
        md5 = hashlib.md5()
        for chunk in self.file.chunks():
            md5.update(chunk)
        return md5.hexdigest()
```
particurarly at line
```
for chunk in self.file.chunks():
```
when he tries to loop over all chunks.

I tried this code with django-1.9.1 and also 1.11.2 and it is all the same.

I made some small changes to debug the problem:
```
@property
    def md5(self):
        print("f0")
        md5 = hashlib.md5()
        print(self.file)
        print(self.file.chunks())
        for chunk in self.file.chunks():
            print("f1")
            md5.update(chunk)
        print("f2")
        return md5.hexdigest()
```
and the output is

> f0
> 
> <generator object File.chunks at 0x7fd3af0f10f8>
> [22/Aug/2017 12:25:14] "POST /upload/chunk/ HTTP/1.1" 500 67

**Comment by tcztzy** [comment]
@rlalik Thanks for reporting.
The problem occurs because Django cannot find your uploaded file.
You can see the [upload function](https://github.com/tcztzy/django-multiple-file-chunked-upload/blob/e95565e91939057e574cbbae8a1e6493a2315d77/upload/models.py#L61), you should replace this function like
```python
def generate_file_path(instance, filename):
    return os.path.join('dsname_'+instance.file_name, filename)
```

**Comment by rlalik** [comment]
Ok, I close this as I found the reason, it was problem in another part of code, I accidentally removed good part of your code and it resulted in the problem. The solution you recommended above is not necessary.
